# -*- coding: utf-8 -*-
"""01.Arithmetic Operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dieWtPvCmdZiOTQ3-g7Uw3Mx-w9WOBNZ

# Operators

## Binary Operator
"""

x = 6
y = 3

print(x+y)        # 9

"""x+2y-1"""

z=2*y
print(x +z-1)   # 11

print(x / y)            # 2.0

"""    (x+y)
    _____
      3
______________
       3
"""



z =( ((x+y) /3) /3 )

print(z)                # 1.0

# Unary Operator
print(-z)               # -1.0

print(7)        # 7

print(+7)       # 7

print(+++7)     # 7

print(-7)        # -7

print(--7)       # 7

print(---7)      # -7

print(----7)     # 7

print(7 -- 5)       # 12

print(7 --- 5)       # 2

print(14 / 2)   # 7.0

print(14 / 3)   # 4.666666666666667

print(14 / 40)  # 0.35

print(14 // 2)   # 7

print(14 // 3)   # 4

print(14 // 40)  # 0

print(14 / 8)     # 1.75

print(14 // 8)    # 1   round down to a small value 1 = min(1, 2)

print(-14 // 8)   # -2  = -2 = min(-2, -1)

print(       (14 / 7))     # float

print(       (14 // 7))    # int

"""/"""

num = 12345

print(num / 10)         #  1234.5

print(num / 100)        #  123.45

print(num / 1000)       #  12.345

print(num / 10000)      #  1.2345

print(num / 100000)     # 0.12345

"""//"""

print(num // 10)        # 1234

print(num // 100)       # 123

print(num // 1000)      # 12

print(num // 10000)     # 1

print(num // 100000)    # 0

"""**

4
 *
2
"""

q=4
w=2
print(q**w)       # 16

"""   -4
 *
2
"""

e=1
r=16
print(e/r)      # 0.0625 = 1/16

print(5 ** 0)       # 1

print(0 ** 5)       # 0

print(2.1 ** 4)     # 19.448100000000004

print(2 ** 4.1)     # 17.148375400580687

# Remove last K digits

num, k = 12345, 3
print(num // (10 ** k)) # 12

print('Hi')
print()
print("I am Mahmoud")
print(3 * 6)
print("Wonderful day")
print("Wonderful \t" "day")

